---
- name: Storage Allocation
  hosts: dscli
  gather_facts: no
 
  tasks:
  - name: Fetch host details
    raw: lshost {{host_id}}
    register: host_detail

  - name: Make a volume
    raw: mkvolume -size {{size}} -unit gb -pool {{pool}} -nomsg
    register: volume_id

  - name: Map volume to host
    raw: mkvdiskhostmap -nomsg -host {{host_id}} {{volume_id.stdout|trim}}
    register: scsi_lun_id

  - name: Debug variable scsi_lun_id
    debug: 
      msg: "<scsilun>{{scsi_lun_id}}</scsilun>"

  - name: Debug variable host_details
    debug:
       msg: "<hostdetail>{{host_detail}}</hostdetail>"
